org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.76
neo_version_range=[26.1.2,)
loader_version_range=[3,)

## Mod Properties
mod_id=havenpebbles
mod_name=HavenPebbles
mod_license=All Rights Reserved
mod_version=1.0.10
mod_group_id=net.cathienova.havenpebbles
mod_authors=CathieNova
mod_description=A mod that makes it possible to get pebbles out of the ground using right click.

## Mod Dependencies
jei_version=29.6.2.31
jei_version_range=[29.6.2,)