modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
    modId="havenpebbles"
    version="${file.jarVersion}"
    displayName="${mod_name}"
    credits=""
    authors="${mod_authors}"
    description='''${mod_description}'''
[[dependencies.havenpebbles]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.havenpebbles]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"