name: Bug report
description: >-
  Please use this template when you have encountered a bug in HavenPebbles.  
  If the issue seems to affect only one mod, please report to them first instead of here.
title: '[Bug]: '
body:
  - type: textarea
    id: repro_steps
    attributes:
      label: Steps to Reproduce the Bug
      description: Please explain what we need to do to cause the bug.
      placeholder: >-
        Example:  
        1. Open the game
        2. Pebbles are not spawning
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: >-
        Please explain what should happen when you follow the steps, if the bug
        were fixed.
      placeholder: >-
        Example:  
        When crouch right clicking on a grass block it should spawn a pebble
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: >-
        Please briefly explain what actually happens when you follow the steps,
        because of the bug.
      placeholder: >-
        Example:  
        When crouch right clicking on a grass block it does nothing
    validations:
      required: true
  - type: input
    id: modpack_url
    attributes:
      label: Mod Pack URL (Optional)
      description: >-
        If you're playing with a mod pack, please include a link to it here.
      placeholder: http://www.Biggest-Modpack-Ever.com
  - type: input
    id: modpack_version
    attributes:
      label: Mod Pack Version (Optional)
      description: >-
        If you're playing with a mod pack, please include its version here.
      placeholder: 0.0.1 Alpha
  - type: textarea
    id: notes
    attributes:
      label: Extra Notes (Optional)
      description: >-
        Optionally, please include anything else you'd like to say about the bug.
      placeholder: >-
        Example:  
        I've tried this with multiple worlds and it still happens.
    validations:
      required: false
  - type: markdown
    attributes:
      value: >-
        ## Sharing your `latest.log`

        In order to diagnose a bug, we will need to see your `latest.log`.  

        To share your `latest.log` here, please follow these steps:


        1. If you don't have it already, find your `latest.log` file.  

        a. [Find your minecraft
        folder](https://stickypiston.co/account/knowledgebase/130/How-do-I-find-my-Minecraft-Folder.html)   

        b. In the minecraft folder, go into the `logs` folder and find the
        `latest.log` file.

        1. Create a Pastebin from the client crash report file, and copy the url.
  - type: input
    id: crashlog
    attributes:
      label: latest.log
      description: Please paste the url to the Pastebin containing your `latest.log` file.
      placeholder: https://pastebin.com/<your_pastebin_id>